[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    [en.params.head]
        tagline = "Policy, Strategy, and History"
    [en.params.social]
        title = "Follow me"
        caption = "Political science and international relations graduate student"
    [en.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."

[pt]
    languageName = "Português"
    contentDir = "content/pt"
    weight = 2
    [pt.params.head]
        tagline = "Política, Estratégia e História"
    [pt.params.social]
        title = "Segue-me"
        caption = "Mestrando em ciência política e relações internacionais"
    [pt.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."